[package]
name = "ssh-grades"
version = "0.1.0"
edition = "2024"

[dependencies]
colored = "3.0.0"
ssh2 = "0.9.5"
directories = "5.0"
keyring = "2.3"
rpassword = "7.3"
serde = { version = "1.0", features = ["derive"] }
toml = "0.8"
anyhow = "1.0" 
